language: python
python:
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
#matrix:
#  include:
#    - python: 3.7
#      dist: xenial
#      sudo: true
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - sudo apt-get install python-dev libxml2-dev libxslt1-dev antiword unrtf poppler-utils pstotext tesseract-ocr flac lame libmad0 libsox-fmt-mp3 sox libjpeg-dev swig libasound2-dev libpulse-dev
  - pip install -r requirements.txt
script:
  - pytest -k "TestPreProcess"
  - pytest -k "TestApi"
before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: ucals/bettertogether
    bucket: bettertogether-deployment
    region: sa-east-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: bettertogether-deployment
    key: latest.zip
    bundle_type: zip
    application: BetterTogether
    deployment_group: BetterTogetherDeployGroup
    region: sa-east-1
    on: *2


# Check the following tutorial to understand deployment:
# https://medium.com/@itsdavidthai/comprehensive-aws-ec2-deployment-with-travisci-guide-7cafa9c754fc
